// flow-typed signature: b5baeb6ce702ca2d061f6f3f27b16d81
// flow-typed version: <<STUB>>/@textpress/eslint-config-textpress_v^0.0.6/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@textpress/eslint-config-textpress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@textpress/eslint-config-textpress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@textpress/eslint-config-textpress/index' {
  declare module.exports: $Exports<'@textpress/eslint-config-textpress'>;
}
declare module '@textpress/eslint-config-textpress/index.js' {
  declare module.exports: $Exports<'@textpress/eslint-config-textpress'>;
}
