// flow-typed signature: 7ec692225d4eaa1d4c540fb258c78e2b
// flow-typed version: <<STUB>>/@textpress/gulp-bump-version_v*/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@textpress/gulp-bump-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@textpress/gulp-bump-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@textpress/gulp-bump-version/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@textpress/gulp-bump-version/lib/index.js' {
  declare module.exports: $Exports<'@textpress/gulp-bump-version/lib/index'>;
}
