// flow-typed signature: 4bd8585df6fe6da012968ba95a354689
// flow-typed version: <<STUB>>/babel-preset-bluebird_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-bluebird'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-bluebird' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-bluebird/main.es5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-bluebird/main.es5.js' {
  declare module.exports: $Exports<'babel-preset-bluebird/main.es5'>;
}
