// flow-typed signature: 95a7c5d87ba9894d9269581cc6b072f1
// flow-typed version: <<STUB>>/gulp-confirm_v^1.0.8/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-confirm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-confirm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-confirm/index' {
  declare module.exports: $Exports<'gulp-confirm'>;
}
declare module 'gulp-confirm/index.js' {
  declare module.exports: $Exports<'gulp-confirm'>;
}
