// flow-typed signature: 1fe79fc918ce04c17c4b148f553bc9d5
// flow-typed version: <<STUB>>/gulp-print_v^5.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-print/gulp-print' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-print/gulp-print.js' {
  declare module.exports: $Exports<'gulp-print/gulp-print'>;
}
